FROM openjdk:8-jdk-alpine
WORKDIR /app

 #Copy maven executable to the image
COPY mvnw .
COPY .mvn .mvn
# Copy the pom.xml file
COPY pom.xml .

# Build all the dependencies in preparation to go offline. 
# This is a separate step so the dependencies will be cached unless 
# the pom.xml file has changed.
#RUN ./mvnw dependency:go-online -B

COPY src src
RUN ./mvnw package -DskipTests 
#RUN mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} mcommandes-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/mcommandes-0.0.1-SNAPSHOT.jar"]